### ISSUE TITLE
开始报错了

### ISSUE THREAD

**Issue by doting8** [nibabashilkk/alipan_auto_sign#11]

**Comment by doting8** [comment]
13s
Run go build &&
go: downloading gopkg.in/yaml.v3 v3.0.[1](https://github.com/doting8/alipan_auto_sign/actions/runs/9217286670/job/25359003210#step:4:1)
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
autoSign/platform.(*AliCloudDisk).getReward(0x95e8d0?, {0xc0004ac380, 0x3[6](https://github.com/doting8/alipan_auto_sign/actions/runs/9217286670/job/25359003210#step:4:7)0}, {0xc00023d4b0, 0x2})
	/home/runner/work/alipan_auto_sign/alipan_auto_sign/platform/ali_cloud_disk.go:93 +0x63b
autoSign/platform.(*AliCloudDisk).qianDao(0x10?, {0xc00001c520?, 0xc0000162a0?})
	/home/runner/work/alipan_auto_sign/alipan_auto_sign/platform/ali_cloud_disk.go:108 +0x[7](https://github.com/doting8/alipan_auto_sign/actions/runs/9217286670/job/25359003210#step:4:8)1
autoSign/platform.(*AliCloudDisk).Run(0xc00001c520?, {0xc00001c440, 0x20}, {0xc00001c520, 0x20})
	/home/runner/work/alipan_auto_sign/alipan_auto_sign/platform/ali_cloud_disk.go:121 +0x4a
main.main()
	/home/runner/work/alipan_auto_sign/alipan_auto_sign/main.go:1[8](https://github.com/doting8/alipan_auto_sign/actions/runs/9217286670/job/25359003210#step:4:9) +0xc6
Error: Process completed with exit code 2.

**Comment by nibabashilkk** [comment]
token咋配的

**Comment by doting8** [comment]
> token咋配的

token 重新确认了一下，就是按照教程配的 的，目前只配了ailiyunpan的refresh_token ，也是报这个错

**Comment by deepinsc2020** [comment]
阿里加了验证了

**Comment by lyhenrique** [comment]
增加了验证

**Comment by doting8** [comment]
wu
